<?php

namespace App\Models\GeneralSettings;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class GeneralSettingsCompanies extends Model
{
    use HasFactory,Notifiable;

    protected $fillable = [
        'name',
        'name_ar',
        'country_id',
        'governorate_id',
        'address',
        'email',
        'phone',
        'vat_number',
        'po_box',
        'logo',
        'primary_currency_id',
        'secondary_currency_id',
        'level_type',
        'parent_company_id',
        'supplier_raw_materials_goods_account_id',
        'supplier_raw_materials_goods_accounting_accounts_class_id',
        'supplier_raw_materials_goods_vat_base_account_id',
        'supplier_raw_materials_goods_vat_accounting_accounts_class_id',
        'supplier_fixed_assets_base_account_id',
        'supplier_fixed_assets_accounting_accounts_class_id',
        'supplier_fixed_assets_vat_base_account_id',
        'supplier_fixed_assets_vat_accounting_accounts_class_id',
        'supplier_services_expenses_base_account_id',
        'supplier_services_expenses_accounting_accounts_class_id',
        'supplier_services_expenses_vat_base_account_id',
        'supplier_services_expenses_vat_accounting_accounts_class_id',
        'supplier_use_same_vat_account',
        'use_same_supplier_account',
        'customer_base_account_id',
        'customer_accounting_accounts_class_id',
        'customer_vat_base_account_id',
        'customer_vat_accounting_accounts_class_id',
        'sales_discount_accounting_accounts_class_id',
        'sales_discount_chart_of_account_id',
        'purchase_discount_accounting_accounts_class_id',
        'purchase_discount_chart_of_account_id',
        'fx_gain_chart_of_account_id',
        'fx_loss_chart_of_account_id',
        'sales_accrual_chart_of_accounts_id',
        'accounts_leading_zeros',
        'ecommerce_website_domain',
        'ecommerce_default_crm_customer_id',
        'ecommerce_default_location_id',
        'company_closing_vat_raw_materials_goods_chart_of_account_id',
        'company_closing_vat_fixed_assets_chart_of_account_id',
        'company_closing_vat_services_expenses_chart_of_account_id',
        'company_closing_vat_sales_chart_of_account_id',
        'company_open_vat_raw_materials_goods_base_account_ids',
        'company_open_vat_fixed_assets_base_account_ids',
        'company_open_vat_services_expenses_base_account_ids',
        'company_open_vat_sales_base_account_ids',
        'company_closing_vat_periodicity',
        'company_closing_fiscal_year_profit_chart_of_account_id',
        'company_closing_fiscal_year_loss_chart_of_account_id',
        'company_lock_before_date',
        'company_lock_except_profiles_ids',
        'reset_quotation_number_on_new_fiscal_year',
        'reset_sales_order_number_on_new_fiscal_year',
        'reset_sales_invoice_number_on_new_fiscal_year',
        'reset_sales_invoice_return_number_on_new_fiscal_year',
        'reset_purchase_order_number_on_new_fiscal_year',
        'reset_purchase_invoice_number_on_new_fiscal_year',
        'reset_purchase_invoice_return_number_on_new_fiscal_year',
        'reset_purchase_invoice_payment_number_on_new_fiscal_year',
        'reset_sales_invoice_payment_number_on_new_fiscal_year',
        'reset_transfer_order_number_on_new_fiscal_year',
        'reset_production_order_number_on_new_fiscal_year',
        'reset_accounting_credit_note_number_on_new_fiscal_year',
        'reset_accounting_debit_note_number_on_new_fiscal_year',
        'reset_ecommerce_order_number_on_new_fiscal_year',
        'reset_customer_purchase_order_number_on_new_fiscal_year',
        'next_customer_number',
        'next_supplier_number',
        'next_location_number',
        'next_inventory_item_number',
        'next_quotation_number',
        'next_customer_purchase_order_number',
        'next_sales_order_number',
        'next_sales_invoice_number',
        'next_sales_invoice_return_number',
        'next_purchase_order_number',
        'next_purchase_invoice_number',
        'next_purchase_invoice_return_number',
        'next_purchase_invoice_payment_number',
        'next_sales_invoice_payment_number',
        'next_transfer_order_number',
        'next_production_order_number',
        'next_accounting_credit_note_number',
        'next_accounting_debit_note_number',
        'next_accounting_expense_number',
        'next_disposal_order_number',
        'max_returned_days',
        'next_ecommerce_order_number',
        'commercial_registration_number',
        'print_name',
        'next_schema_number',
        'use_soft_booking_for_sales_orders',
    ];
}
